steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile.web
      - --tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile
      - --build-arg=COMMIT_SHA=${_TAG}
      - --tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/adk:${_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/adk:${_TAG}
substitutions:
  _REGION: us-east1
  _REPOSITORY: bateriaspower
  _TAG: v1
timeout: 1800s
